### ISSUE TITLE
Create new StepDefinition WIzard does not work

### ISSUE THREAD

**Issue by Doogiemuc** [cucumber/cucumber-eclipse#157] opened 2016-04-18 08:36 UTC
I cannot create a Step-Definition class with the File->New  wizard:

IllegalArgumentException: HIDDEN   When createing a new "StepDefinition Class"

```
Exception:java.lang.IllegalArgumentException: HIDDEN
     at org.eclipse.swt.SWT.error(SWT.java:4472)
     at org.eclipse.swt.SWT.error(SWT.java:4406)
     at org.eclipse.swt.SWT.error(SWT.java:4377)
     at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
     at org.eclipse.swt.widgets.Text.setText(Text.java:2285)
     at cucumber.eclipse.editor.wizard.NewStepDefFileWizardPage.initialize(NewStepDefFileWizardPage.java:175)
     at cucumber.eclipse.editor.wizard.NewStepDefFileWizardPage.createControl(NewStepDefFileWizardPage.java:83)
     at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:175)
     at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:705)
     at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1153)
     at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1211)
     at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1208)
```

**Comment by ilanpillemer** [comment] 2016-04-19 12:21
I also got an error. @girijant is this working for you?

**Comment by girijant** [comment] 2016-04-20 17:35
Thanks **ilanpillemer ** for finding the root cause of above issue. I always tested through maximized feature file. Let me first test and will fix the issue.

**Comment by girijant** [comment] 2016-04-22 15:11
@ilanpillemer : I got same error : 'Argument cannot be null' with exception stack while creating new "StepDefinition Class" after right click on any project package : File > New > Others > 'Cucumber' > Step-Definition class , instead from Normal File Menu.
Is it same for you...???

@Doogiemuc : I am not getting the error : 'IllegalArgumentException: HIDDEN' When creating a new "StepDefinition Class" from Normal File Menu like : File > New > Others > 'Cucumber' > Step-Definition class  : 
 - Project Name : {project-dir}/src/java or {project-dir}/src/test
- Package Name : {Package name}
- Class Name : {FileName/FileName.java}

Can you please specify the exact steps for the above issues, so that  I can do a quick fix.

**Comment by ilanpillemer** [comment] 2016-04-23 08:16
Yes. Same for me.

**Comment by girijant** [comment] 2016-04-23 08:51
@ilanpillemer : I've fixed your issue and waiting for Doogiemuc's reply.

**Comment by girijant** [comment] 2016-05-07 15:10
@Doogiemuc : Any update from your side? Else I can pull a request.

**Comment by girijant** [comment] 2016-05-08 07:08
@ilanpillemer : Issue 'Argument cannot be null' with exception stack is resolved in 'o.0.15' version.
You can create new "StepDefinition Class" after right click on any project package : File > New > Others > 'Cucumber' > Step-Definition class , instead from Normal File Menu.

**Comment by Doogiemuc** [comment] 2016-07-25 14:51
Thank you very much for following up on this. I didn't have the time to re-test, but I am sure you did a god job.   I just wanted to raise the issue, because I thought it was a pretty basic thing that many cucumber beginners might stumble upon.

**Comment by girijant** [comment] 2017-03-16 05:22
@ilanpillemer : I had already Fixed this issue. This issue is still in 'Open' state. Please close it.

**Comment by girijant** [comment] 2017-11-04 11:22
I had already Fixed this issue. So closing this ticket.

**Closed by girijant** 2017-11-04 11:22 UTC
