### ISSUE TITLE
not able to found file in step definition using . operator

### ISSUE THREAD

**Issue by sharma-rakesh** [cucumber/cucumber-eclipse#118] opened 2015-05-07 10:40 UTC

**Comment by sharma-rakesh** [comment] 2015-05-07 10:43
able to find file using absolute path,but not using . operator . how ever same code works with plain java main method . 

cucumber is trying to search my resource files in eclips directory . not in project directory

**Comment by daveychu** [comment] 2015-05-09 09:35
Can you attach an example?

**Comment by sharma-rakesh** [comment] 2015-05-14 09:24
File f = new File("./src/values.properties");						
input = new FileInputStream(f);

this value.properties file is being searched in eclipse folder not in  project folder

**Comment by sharma-rakesh** [comment] 2015-05-14 09:24
File f = new File("./src/values.properties");			
			System.out.println(propertyName  + f.exists());			
			input = new FileInputStream(f);

**Comment by lxbzmy** [comment] 2015-07-16 05:10
I can confirm this Bug.
The problem is  plugin runner 's working directory is eclipse installation location. not the project directory of feature file.

**Comment by pdincau** [comment] 2015-08-11 14:54
any news about this issue?

**Comment by lxbzmy** [comment] 2015-08-12 01:34
@pdincau ，already fixed in master branch. clone and mvn package.

**Comment by pdincau** [comment] 2015-08-12 07:39
@lxbzmy thanks, can you point out the commit fixing this issue?

**Comment by xpepper** [comment] 2015-08-12 08:14
Hi @lxbzmy, 
can we close this issue then?

thank you!

**Comment by ilanpillemer** [comment] 2015-08-12 10:53
Anyone up to cutting a new release as there is quite a lot in master that
is not yet released to the plugin that is available.

**Comment by girijant** [comment] 2017-11-24 11:53
@lxbzmy,
Closing this issue as per your comment. If you still found issue, please share your comments with proper snapshots/logs.

Thanks,
-Girija

**Closed by girijant** 2017-11-24 11:53 UTC
