### ISSUE TITLE
Custom Type Registry reporting not found

### ISSUE THREAD

**Issue by melloware** [cucumber/cucumber-eclipse#362] opened 2019-05-02 13:23 UTC
Cucumber Eclipse:   1.0.0.201904151253	
Eclipse: 2019-03 (4.11.0)

**Custom Type Registry:**
```java
public class OasisTypeRegistry implements TypeRegistryConfigurer {

   @Override
   public void configureTypeRegistry(final TypeRegistry typeRegistry) {
      typeRegistry.defineParameterType(new ParameterType<>("dateTime", "(\\d+)/(\\d+)/(\\d+) (\\d+):(\\d+)",
               DateTime.class, new CaptureGroupTransformer<DateTime>() {
                  @Override
                  public DateTime transform(final String[] args) throws Throwable {
                     return new DateTime(Integer.parseInt(args[2]), Integer.parseInt(args[0]),
                              Integer.parseInt(args[1]), Integer.parseInt(args[3]), Integer.parseInt(args[4]));
                  }
               }, false, false));

      typeRegistry.defineParameterType(new ParameterType<>("dateTimestamp", "(\\d+)/(\\d+)/(\\d+) (\\d+):(\\d+):(\\d+)",
               DateTime.class, new CaptureGroupTransformer<DateTime>() {
                  @Override
                  public DateTime transform(final String[] args) throws Throwable {
                     return new DateTime(Integer.parseInt(args[2]), Integer.parseInt(args[0]),
                              Integer.parseInt(args[1]), Integer.parseInt(args[3]), Integer.parseInt(args[4]),
                              Integer.parseInt(args[5]));
                  }
               }, false, false));

   }

   @Override
   public Locale locale() {
      return Locale.ENGLISH;
   }
}
```

**Step:**

```java
   @Given("the current time is {dateTime}")
   public void the_current_time_is(final DateTime time) throws Throwable {
      World.TIME_MACHINE.warp(time);
   }
```

In my Gherkin its reporting as the step is not resolving:

![image](https://user-images.githubusercontent.com/4399574/57078321-0aa8d900-6cbc-11e9-8bb3-c76a8c83b947.png)

**Comment by laeubi** [comment] 2019-05-03 10:33
You must

1. use the latest snap-shot build
2. enable java backend in the project settings
3. rebuild the project

**Comment by melloware** [comment] 2019-05-03 11:38
I am on the SNAPSHOT release  1.0.0.201904151253 as I followed the SNAPSHOT instructions.

I enabled Java Backend:
![image](https://user-images.githubusercontent.com/4399574/57135124-59b34480-6d76-11e9-9f9a-24e4d754231f.png)

I rebuilt my project and I still have the same exact results that it is not finding my custom registry.  When I run the tests the code works fine so its definitely configured correctly.

**Comment by laeubi** [comment] 2019-05-03 14:20
Where is the factory located? It must be located in the package named in the glue and in the same project as the feature file.

**Comment by melloware** [comment] 2019-05-03 14:28
Yep that is exactly the case it is located in my glue code directory listed above in the screenshot.

**Comment by RusmanCool** [comment] 2019-07-25 18:02
@laeubi , I can confirm that the issue is still present even with the plugin v1.0.0.201907020018. I had followed above steps and a step in *.feature is still marked as not found.

**Comment by laeubi** [comment] 2021-09-14 09:08
We are currently developing a new version of the cucumber-plugin with improved support for more recent cucumber versions, if you like try out the following update-site (please uninstall the old plugin before):
https://cucumber.github.io/cucumber-eclipse/update-site/main/

**Comment by laeubi** [comment] 2021-09-14 09:08
There will be no more work on this for v1.x unless someone opens a PR to fix this.

**Closed by laeubi** 2021-09-14 09:08 UTC
Labels: v1.x
