### ISSUE TITLE
Duplicate Step definitions

### ISSUE THREAD

**Issue by akshaykamath** [cucumber/cucumber-eclipse#211] opened 2017-10-29 18:17 UTC
When I try to use the content assist feature, I get duplicate step definitions. Is this a known issue?

**Comment by girijant** [comment] 2017-10-30 13:52
Content assistance populates all step definitions available in your step definition java file. You might have duplicate steps in your step definition java file.

**Comment by akshaykamath** [comment] 2017-10-31 00:54
Hi @girijant, 

I also checked this with other users who were also facing this issue. 

You can also refer my Step Definition file here: https://github.com/akshaykamath/cucumber-poc/blob/master/src/test/java/com/poc/cucumber/calculator/StepDefinition.java

So I am not sure if this is caused due to duplicate steps. Please let me know if I may have overlooked something.

I also tried debugging this issue on my machine. It looks like it is caused due to there being two implementations of IStepDefinitions in :
1. cucumber.eclipse.editor.steps.jdt.StepDefinitions and
2. cucumber.eclipse.steps.jdt.StepDefinitions

So the steps are loaded twice during ExtensionRegistryStepProvider.reloadSteps() method.

**Comment by girijant** [comment] 2017-11-02 07:14
Hi @akshaykamath,

Thanks for your analysis. As far I know this issue was not due to the implementions of two 'StepDefinitions' file in two different packages. The purpose of redefining 'cucumber.eclipse.steps.jdt.StepDefinitions' class in 'cucumber.eclipse.editor.steps.jdt' package is only to avoid plugin-dependency conflicts. This 'cucumber.eclipse.editor.steps.jdt.StepDefinitions' class supports for reusing of Step-Definitions from external JAR(.class) exists in your class-path. Also Reads the package name of external JAR from 'User Settings' of Cucumber-Preference page and Populate the step proposals from external JAR.

My team is extensively using this content-assistance feature, but never came across with such issue. I would like to request you don't update any file, else it would be difficult for me to debug. Let me first debug with your sample 'StepDefinition.java' file and will let you know.
Please attach detail snap-shots of both steps in content-assistance popup with mouse over on both steps.

Thanks,
-Girija

**Comment by akshaykamath** [comment] 2017-11-02 09:24
![scr-shot-cucumber](https://user-images.githubusercontent.com/13991499/32317996-c55ec5e4-bf83-11e7-82fd-25675e621dea.png)
@girijant Thanks for looking into this. I have not updated the files since I am not familiar with this code :) 

I have attached a screen shot for your reference, however since you mention that you have been using it without facing this issue, it could be some issue on my machine. 

I am using Eclipse Java EE IDE for Web Developers Version: Neon.3 Release (4.6.3)

**Comment by girijant** [comment] 2017-11-03 13:11
@akshaykamath,
I am able to reproduce this issue in my enviroment. This issue was not exists with prior plugin version '0.0.15'. Main root cause of this issue is due to the redefining of same code in 'cucumber.eclipse.steps.jdt.StepDefinitions' class i.e. updated by other developer. Now issue is got fixed in my local environment and preparing a build with latest version. I'll update you once it's done. 

Thanks,
-Girija

**Comment by girijant** [comment] 2017-11-03 14:58
@akshaykamath,
Issue is got fixed and available in latest plugin version '0.0.18' with below summary:
- Fixed for duplicate step definitions
- Fixed for content-assistance with an improvised feature i.e. Steps can be populated based on both starts-with and contains with any words. 
Please update plugin with latest version and let me know if any issue. 

Thanks, 
-Girija

**Comment by girijant** [comment] 2017-11-04 11:15
Issue is got fixed and available in latest plugin version '0.0.18' with below summary:
- Fixed for duplicate step definitions
- Fixed for content-assistance with an improvised feature i.e. Steps can be populated based on both starts-with and contains with any words.
Please update plugin with latest version and let me know if any issue.

Thanks,
-Girija

**Closed by girijant** 2017-11-04 11:15 UTC
Labels: bug
