### ISSUE TITLE
Getting warning in the feature file -"Step does not have a matching glue code"

### ISSUE THREAD

**Issue by desai-padmini** [cucumber/cucumber-eclipse#257] opened 2018-03-26 16:56 UTC
Hi all, I am new to cucumber-selenium and getting a warning message "step does not have a matching glue code" in my feature file. I have downloaded the latest cucumber eclipse plugin version-0.0.21 as mentioned in issue#207 but still getting the same warning message and my script runs fine but it is not reading the test data I have defined in my feature file. 
I am using eclipse Neon version 3.0. Can someone please help me in resolving this issue?

I have added some screenshots that can help understand the issue further.
![image](https://user-images.githubusercontent.com/37809244/37920378-51c5cdaa-30ec-11e8-9efd-cb4c6b131e93.png)
![image](https://user-images.githubusercontent.com/37809244/37920400-5f5ce66a-30ec-11e8-96a1-e913cbf087c2.png)
![image](https://user-images.githubusercontent.com/37809244/37920418-6b3ace5c-30ec-11e8-84ca-d59b0e824e72.png)
![image](https://user-images.githubusercontent.com/37809244/37920474-8abadca4-30ec-11e8-83f3-ad74608497cb.png)
![image](https://user-images.githubusercontent.com/37809244/37920479-90a8aa10-30ec-11e8-96b8-bd609af79e1d.png)

Here is my project structure
![image](https://user-images.githubusercontent.com/37809244/37927585-24eb7c6c-3100-11e8-990f-5bff9c3f21a1.png)

**Comment by girijant** [comment] 2018-03-27 20:11
@desai-padmini,
Did you specified steps in your  step definition file java file??

Thanks,
Girija

**Comment by desai-padmini** [comment] 2018-03-27 20:15
Thank you for getting back to me. Yes, I have defined code for the email address in the java file as follows
![image](https://user-images.githubusercontent.com/37809244/37992506-8be57cde-31d1-11e8-8d64-0ea3f00e5586.png)

I was expecting when the file runs to read email address - TX_reg1@test.com but it is not reading this input and passing the value when the script actually runs.

**Comment by desai-padmini** [comment] 2018-03-27 20:16
This is what I see after running my script.
![image](https://user-images.githubusercontent.com/37809244/37992622-dfd11efc-31d1-11e8-9b0b-3ee0152c72ac.png)

**Comment by girijant** [comment] 2018-03-27 20:21
Please try to remove double slashes before .com and close all the feature files and reopen the feature file.

Thanks
GIRIJA

**Comment by girijant** [comment] 2018-03-27 20:37
@desai-padmini,
Ignore my first comment and Move your 'features' folder containig feature files into src/test/resources folder and close all the feature files and reopen the feature file.

Thanks
GIRIJA

**Comment by desai-padmini** [comment] 2018-03-27 20:51
I am still getting the same error
![image](https://user-images.githubusercontent.com/37809244/37994247-932540f6-31d6-11e8-9028-0f7837dc531c.png)

![image](https://user-images.githubusercontent.com/37809244/37994292-bc1f73aa-31d6-11e8-827f-b3f78e74df21.png)

**Comment by girijant** [comment] 2018-03-28 06:25
@desai-padmini,
Rename 'features' dir from src/test/resources with 'StepDefinition' and close all the feature files and reopen the feature file.

Thanks
GIRIJA

**Comment by laeubi** [comment] 2018-03-28 08:16
I recently fixed some things in the area of stepdefintion parsing in java files, so do you have a chance to build the latest master and try if the problem is fixed with that version?
Have you tried to remove the space in front of your expression?

**Comment by desai-padmini** [comment] 2018-03-28 13:45
Thank you Girija for the sugestion but I am still getting the error.
![image](https://user-images.githubusercontent.com/37809244/38032626-b99de39a-3263-11e8-9d29-2885be9cb1e1.png)

Thank you Christopher for the suggestion. But I am not sure I understand what is to be done. Can you please explain in terms of which version and for what I should download. As suggested in issue#207 I downloaded latest version of cucumber-selenium (0.0.21) and have included in my project.
Also where should I remove a space in the expression? Are you referring to expression in the java code or feature file? Can you please let know?

**Comment by girijant** [comment] 2018-03-28 14:02
@desai-padmini,
Please retry only by removing the space from '^ enters' by '^enters' from the @when annotation of your step definition java file.

Thanks,
Girija

**Comment by desai-padmini** [comment] 2018-03-28 14:14
Removed the space but still the same.
![image](https://user-images.githubusercontent.com/37809244/38034636-561de360-3268-11e8-8b4d-b539ef0fce1f.png)
![image](https://user-images.githubusercontent.com/37809244/38034662-616db614-3268-11e8-8f64-0edd251758e0.png)

**Comment by girijant** [comment] 2018-03-28 16:39
@desai-padmini,
Share your entire project as zip, I will look into it.

Thanks,
Girija

**Comment by desai-padmini** [comment] 2018-03-29 17:00
Hi Girija, Sorry for the delayed response. I restructured my project and now defined the feature file under src/test/feature and it is no longer throwing the warning message and also taking the test data that I have defined in my feature file. 
![image](https://user-images.githubusercontent.com/37809244/38102138-fb1637ca-3347-11e8-9080-c7dce2b43e5a.png)

Earlier I had defined the feature file outside independently like this
![image](https://user-images.githubusercontent.com/37809244/38102328-8220d432-3348-11e8-866c-a3253f0f9421.png)

Is there a reason we have to define feature file under src/test/feature verses independently?
I am still learning this, hence sorry for a basic question.

Thanks,
Padmini

**Comment by djavvadi** [comment] 2018-06-11 12:13
I am facing the same issue.

**Comment by ranmatrix** [comment] 2018-08-08 17:34
Can you try the following
Move Feature file under -->src/test/resource <feature files>
Move step definition file under --> src/test/java <definition file with your package structure>
Rename your definition file as StepDefinitionSubmitBCLoanApplication.java

The above worked for me...

**Comment by prithviraaj** [comment] 2018-10-05 20:43
Keep the Feature file in the resources folder. If you have changed anything in feature file like space, tab etc. then close the feature file and then open it. The warning messages will gone. I just did the same and now its working fine for me.

**Comment by asmita4413** [comment] 2018-11-02 02:48
@prithviraaj  thanks
I followed the same steps and working fine for me

**Comment by girijant** [comment] 2018-11-29 11:00
Closing this ticket.

**Closed by girijant** 2018-11-29 11:00 UTC
Labels: cannot reproduce

**Comment by laisportugal** [comment] 2019-03-06 21:29
> Please try to remove double slashes before .com and close all the feature files and reopen the feature file.

Thank you! I had the same issue and it worked for me

**Comment by dvarshney86** [comment] 2019-09-13 14:06
I tried doing all the provided suggestions, but still facing the same problem. Please see the attached screenshot...
![image](https://user-images.githubusercontent.com/21123194/64868835-67d87200-d640-11e9-98fa-3428512eaf74.png)

**Comment by qvdk** [comment] 2019-09-13 15:53
@codermvn please could your provide more information: Eclipse version, Cucumber plugin version, and your project description. Maybe a simple project where the issue is reproductible ?

**Comment by codermvn** [comment] 2019-09-16 12:53
@girijant @qvdk 
Code is attached for you to review.

**Comment by codermvn** [comment] 2019-09-20 14:12
> @codermvn please could your provide more information: Eclipse version, Cucumber plugin version, and your project description. Maybe a simple project where the issue is reproductible ?

@qvdk @girijant You can check the link pls on issue #207

**Comment by giri-gonzai** [comment] 2019-10-03 08:44
Just close the feature file after saving and reopen. Works fine for me.

**Comment by paiamrutha88** [comment] 2019-11-13 03:50
I have followed all options mentioned above but warning are not just doing away from .feature file

**Comment by qvdk** [comment] 2019-11-13 08:49
@paiamrutha88 can you provide eclipse version and cucumber eclipse plugin version you are using please ?

**Comment by paiamrutha88** [comment] 2019-11-13 08:57
> @paiamrutha88 can you provide eclipse version and cucumber eclipse plugin version you are using please ?

Eclipse Mylyn 4.9.0
Cucumber eclipse Plugin  0.0.23.201811220126

**Comment by qvdk** [comment] 2019-11-13 09:12
@paiamrutha88 Please use the latest version: https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot

**Comment by paiamrutha88** [comment] 2019-11-13 09:25
> @paiamrutha88 Please use the latest version: https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot

Not sure why the one I installed is not latest as I installed it couple of days ago  using eclipse marketplace.
I will try updating it with the link you gave and check

thanks!

**Comment by w2a** [comment] 2019-11-26 11:57
Here are couple of things you need to do:

1. Install this plugin (Go to Eclipse market place and install the same):

https://cucumber.github.io/cucumber-eclipse-update-site-snapshot



2. Right click on your project --> configure --> convert to Cucumber project

And finally it will work

Thanks,
Rahul Arora
Director & Trainer - http://www.way2automation.com

**Comment by RaphaelStark** [comment] 2020-01-25 00:04
Hi Guys, this problem too occur in my project but, already resolved with flow steps: 
1. go to site https://github.com/cucumber/cucumber-eclipse#follow-the-latest-snapshot
2. or copy this link and click an Help > Install new sotfware 
3. if already install old verssion he will do update. 
4. select new version display on screen 
5. re-start your IDE 

Done this problem resolved

**Comment by BhagyaJan** [comment] 2020-03-07 16:19
I got this issue and After clean and build the project in eclipse issue has been resolved.

**Comment by manishthackray** [comment] 2020-06-01 18:20
https://github.com/cucumber/cucumber-eclipse/wiki/Uninstall-the-older-version-of-cucumber-eclipse-plugin

- If you have updated cucumber eclipse plugin then 
- just uninstall (eclipse will restart)and reinstall cucumber eclipse plugin again(eclipse again restarts)
- try now

**Comment by bssindiana** [comment] 2020-06-13 10:45
I have just installed the following Eclipse Version in my Windoes 64 desktop:
Details:
Eclipse IDE for Java Developers
Version: 2020-03 (4.15.0)
Build id: 20200313-1211

I have also installed the Cucumber Plugin:
Cucumber Eclipse Plugin 1.0.0.202005150629

Now, I have imported my existing project that has all setups configured properly and we ran and tested earlier on Intellij. When, we did same for Eclipse, it is unable to identify the Glue Code though all settings and codes existed as said. I also tried to project --> configure --> convert to Cucumber project and restarted System/ Eclipse everything. Still no luck. I tried once with @StepDefAnnotation but was also not working. I want to know, is this a Bug in Eclipse? If yes Is there a WayOut or should we wait for more stable eclipse release?

**Comment by simonezampinistud** [comment] 2020-07-07 16:18
Is it possible to "glue code" that is in a different project?
(JUnit Eclipse plugin runs correctly)

**Comment by qvdk** [comment] 2020-07-08 12:44
Hello @simonezampinistud 

The plugin supports step definitions from dependencies, be sure to use the latest version.

If you need to update follow the [instruction](https://github.com/cucumber/cucumber-eclipse/issues/257#issuecomment-578349189) from the previous comment of @RaphaelStark in this thread.

**Comment by thangabalan43** [comment] 2020-07-09 06:48
erer

**Comment by fannymagnet69** [comment] 2023-12-02 00:22
I am also getting a warning there. Can anyone help

**Comment by laeubi** [comment] 2023-12-02 05:16
Please use the latest snapshot (see readme) as the 1.x version lacks support for recent Cucumber versions.

**Comment by nitinsdettech** [comment] 2024-09-05 14:58
For a quick solution without update is to close the feature file and refresh the project. It worked for me.

**Comment by panel-prized** [comment] 2025-01-30 11:36
@girijant https://stackdev.space/questions/executing-cucumber-tests-using-behavior-driven-development-bdd-within-eclipse
