### ISSUE TITLE
Internationalization (i18n) not recognized

### ISSUE THREAD

**Issue by Dapangma** [cucumber/cucumber-eclipse#282] opened 2018-09-26 07:07 UTC
I am trying to use Gherkin in French, which is supposed to be supported.
But the term 'Fonctionnalité' is not recognized ; Cucumber Eclipse says missing 'Feature'.
![naturaleclipsefrench](https://user-images.githubusercontent.com/13729452/46062827-4a7a7180-c16b-11e8-861b-2a5dd43a7fb2.png)

**Comment by laeubi** [comment] 2018-11-05 07:55
Can you provide an example feature file that cause this?

**Comment by qvdk** [comment] 2018-11-17 11:40
I can reproduce this issue with the following sample. Nor the syntax highlighter, nor the lexical parser seem to recognize the translated gherkin file.

**French keywords are not highlighted:  `Fonctionnalité`, `Scénario`, `Et`, etc.**

![screenshot from 2018-11-17 12-19-20](https://user-images.githubusercontent.com/6142398/48660529-4e3bbd80-ea63-11e8-85b1-d1d8b841859c.png)

**Erroneous alert**

![syntax error](https://user-images.githubusercontent.com/6142398/48660532-53990800-ea63-11e8-9a5e-f8cf4d1b3248.png)


**French gherkin sample**
```
#Author: your.email@your.domain.com
#Keywords Summary :
#Feature: List of scenarios.
#Scenario: Business rule through list of steps with arguments.
#Given: Some precondition step
#When: Some key actions
#Then: To observe outcomes or validation
#And,But: To enumerate more Given,When,Then steps
#Scenario Outline: List of steps for data-driven as an Examples and <placeholder>
#Examples: Container for s table
#Background: List of steps run before each of the scenarios
#""" (Doc Strings)
#| (Data Tables)
#@ (Tags/Labels):To group Scenarios
#<> (placeholder)
#""
## (Comments)
#Sample Feature Definition Template
@tag
Fonctionnalité: Title of your feature
  I want to use this template for my feature file

  @tag1
  Scénario: Title of your scenario
    Etant donné I want to write a step with precondition
    Et some other precondition
    Quand I complete action
    Et some other action
    Et yet another action
    Alors I validate the outcomes
    Et check more outcomes

  @tag2
  Plan de scénario: Title of your scenario outline
    Etant donné I want to write a step with <name>
    Quand I check for the <value> in step
    Alors I verify the <status> in step

    Exemples: 
      | name  | value | status  |
      | name1 |     5 | success |
      | name2 |     7 | Fail    |
```

I also find the list of the [expected supported keywords](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json)

**Comment by qvdk** [comment] 2018-11-23 23:36
Finally, I can not reproduce. I forget the comment ` language: fr` in my previous sample.
The i18n works for me.

Eclipse 
Version: 2018-09 (4.9.0)
Build id: 20180917-1800

Cucumber Eclipse Feature: 0.0.23.201811220126

![peek 2018-11-24 00-33](https://user-images.githubusercontent.com/6142398/48962471-acdfca80-ef80-11e8-916c-980dcb3d277e.gif)

**Comment by girijant** [comment] 2018-11-29 10:41
Closing this ticket.

**Closed by girijant** 2018-11-29 10:41 UTC
Labels: cannot reproduce
