### ISSUE TITLE
does not have a matching glue code

### ISSUE THREAD

**Issue by jeffshawn** [cucumber/cucumber-eclipse#207] opened 2017-08-25 09:43 UTC
When I just create a new feature file ,I got the warn info.  what's the problem?
![qq 20170825173437](https://user-images.githubusercontent.com/30891541/29708866-e1035e56-89bc-11e7-9199-628e38dd7674.png)
![qq 20170825173722](https://user-images.githubusercontent.com/30891541/29708867-e10f31cc-89bc-11e7-8542-c5e47ff1e543.png)
![qq 20170825173749](https://user-images.githubusercontent.com/30891541/29708868-e111568c-89bc-11e7-8cc8-cdb70daff181.png)
![qq 20170825174135](https://user-images.githubusercontent.com/30891541/29708870-e131ac98-89bc-11e7-807f-a8cb3eaa1ae3.png)

**Comment by tts-ll** [comment] 2017-11-14 17:14
I experience the same issue with Spring Tool Suite Eclipse Oxygen (4.7.0)

**Comment by norman-knott** [comment] 2017-11-16 13:19
I also get the warnings in eclipse EE 4.6.3. Running the hole file is not a problem. But the not found steps code makes it less useful.

**Comment by girijant** [comment] 2017-11-16 15:58
@norman-knott @jeffshawn @tts-ll,
Please share your cucumber-eclipse plugin version for better investigation.

**Comment by norman-knott** [comment] 2017-11-16 15:59
0.0.17.201704062133

**Comment by girijant** [comment] 2017-11-16 16:09
@norman-knott,
Thanks for your quick reply. We never came across this issue by extensively using this plugin.
Can you please try once with latest version plugin after uninstalling the older version by referring https://github.com/cucumber/cucumber-eclipse/wiki/Uninstall-the-older-version-of-cucumber-eclipse-plugin.

**Comment by norman-knott** [comment] 2017-11-16 17:03
@girijant The new still gives the warning.

I find this on stdout of Eclipse every time I open a feature file:
`Load JDTStepDefinitions:getSteps()....In package : cucumber.eclipse.editor.steps.jdt
JDTStepDefinitions:STEPS = []`

If this help a bit.

**Comment by girijant** [comment] 2017-11-18 09:25
@norman-knott,
I am not seeing above stdout from Eclipse. Please share your plugin version. Is it '0.0.18.201711040925' ??

**Comment by norman-knott** [comment] 2017-11-19 10:12
@girijant Yepp, `0.0.18.201711040925`. That's my version now.

**Comment by akshaykamath** [comment] 2017-11-19 19:36
@norman-knott this may seem like a silly question, but I am assuming that you are getting a warning in the editor while opening the feature files. Can you please confirm if you have the matching glue code(step definitions in the code files) for each of  your steps? It is also worth noting that the matching step definitions need to be in the same package as the feature file.

For example, note that my feature files are under the following package in the resources folder.
Package name: com.poc.cucumber.calculator 
Source Link:
https://github.com/akshaykamath/cucumber-poc/blob/master/src/test/resources/com/poc/cucumber/calculator/calculator.feature

And my matching step definition files are listed in the test folder under the same package.
Source Link: https://github.com/akshaykamath/cucumber-poc/blob/master/src/test/java/com/poc/cucumber/calculator/StepDefinition.java 

Let me know if this helps.

Thanks :)

**Comment by girijant** [comment] 2017-11-20 06:48
@norman-knott,
Trying to fix the below unnecessary logs from Eclipse stdout:
_Load JDTStepDefinitions:getSteps()....In package : cucumber.eclipse.editor.steps.jdt JDTStepDefinitions:STEPS = []_

**Comment by girijant** [comment] 2017-11-24 11:34
@norman-knott,
Fixed for the unnecessary logs from Eclipse stdout in '0.0.19' latest version. Are you still facing same issue by seeing suggestion of @akshaykamath ??

**Comment by norman-knott** [comment] 2017-11-24 12:41
@akshaykamath Sorry, missed the notification. Will check this tomorrow.

@girijant Thanks for removing the vaxing log :)

**Comment by girijant** [comment] 2017-11-25 06:18
@norman-knott,
Glad to publish Cucumber-Eclipse plugin as a **Zip** file which can be downloaded and installed from your local system.

Please download the **plugin-zip**(cucumber-eclipse-plugin-0.0.19-SNAPSHOT.zip) from the latest version(0.0.19-SNAPSHOT) directory of below url:
- https://github.com/cucumber/cucumber-eclipse/tree/master/cucumber.eclipse.download/download

Also refer our [Plugin-Download/Installation-Wiki](https://github.com/cucumber/cucumber-eclipse/wiki/Download-and-Install-Plugin-From-Zip) for detail information.

Please try and confirm us. We are waiting for your response.

Thanks,
-Girija

**Comment by norman-knott** [comment] 2017-11-25 10:47
@akshaykamath Looks like not all step code is in the same package. But it is very much code, and to be sure I will do a simple test on a new workspace. In two or three days.
@girijant With these tests I also try the new version.

**Comment by norman-knott** [comment] 2017-11-27 14:35
@akshaykamath Even with the simple maven test project provided in the ZIP 
[test.tar.gz](https://github.com/cucumber/cucumber-eclipse/files/1506203/test.tar.gz)
does the editor show the warnings.
![image](https://user-images.githubusercontent.com/18596176/33271747-07fcf01e-d380-11e7-8a57-6ca04b8d212c.png)

![image](https://user-images.githubusercontent.com/18596176/33271812-300ca3ec-d380-11e7-9eec-27b59aaac898.png)

**Comment by norman-knott** [comment] 2017-11-27 14:36
@girijant Couldn't get to install the new version yet. Sorry.

**Comment by akshaykamath** [comment] 2017-11-28 01:13
@norman-knott @girijant This seems like a valid issue. It looks like the plugin does not identify the step definitions that are defined using java 8 lambda expressions. However, the moment you add annotated step definition the warning goes away. 

You can refer this project:
Step Def File:
 https://github.com/akshaykamath/cucumber-poc/blob/master/src/test/java/com/poc/cucumber/StepDefinitionLambda.java#L17

Feature file:
https://github.com/akshaykamath/cucumber-poc/blob/master/src/test/resources/com/poc/cucumber/calculator.feature#L8

If we remove the commented portion of the StepDefinitionLambda.java, the warning is removed from the feature file.

**Comment by girijant** [comment] 2017-11-28 05:20
@akshaykamath, 
Thanks for the quick analysis. I already aware of this issue with java8 environment which is already logged in #175 ticket. Anyway I have to fix it. Also thanks for sharing the project.

**Comment by norman-knott** [comment] 2017-11-28 10:21
@akshaykamath @girijant I glad to help. My colleagues are nagging at me to use IntelliJ. But with a fix for this problem, there is one reason less. ^^

**Comment by girijant** [comment] 2017-11-28 11:16
@norman-knott,
By referring sampe project of @akshaykamath, looking into these tickets #223 and #175 as a high priority request. As of my understanding there are two fixes required for these issues in java8 environment:
- Matching glue-code
- Content Assistance improvement

Thanks,
-Girija

**Comment by norman-knott** [comment] 2017-11-28 14:03
@girijant I've installed the version 0.0.19 from the ZIP. The log does not appear when I open a feature file now.

Thanks 👍

**Comment by justrad** [comment] 2017-12-01 16:36
Another issue I've seen for missing matching step def:

Scenario Outline: Guidance package is purchased as an upgrade from Security
    Given an enrolled vehicle
    And a <Payment Plan> Security package is Active
    When Guidance package is purchased as an upgrade
    Then the Guidance package is Active
    And the <Payment Plan> Security package is Active

    Examples: 
      | Payment Plan |
      | Prepaid      |
      | Monthly      |

-- Feature only will show matching glue code if we use the step def as:

    @When("^a (.+) Security package is Active$")
    public void activitSecurityPackage(String packageType) {

    }

-- Will not find matching glue code, but will work at runtime if we do:

    @When("^a Prepaid Security package is Active$")
    public void activitSecurityPackage(String packageType) {

    }

    @When("^a Monthly Security package is Active$")
    public void activitSecurityPackage(String packageType) {

    }

**Comment by justrad** [comment] 2017-12-01 16:36
Another issue I've seen for missing matching step def:

Scenario Outline: Guidance package is purchased as an upgrade from Security
    Given an enrolled vehicle
    And a <Payment Plan> Security package is Active
    When Guidance package is purchased as an upgrade
    Then the Guidance package is Active
    And the <Payment Plan> Security package is Active

    Examples: 
      | Payment Plan |
      | Prepaid      |
      | Monthly      |

-- Feature only will show matching glue code if we use the step def as:

    @When("^a (.+) Security package is Active$")
    public void activitSecurityPackage(String packageType) {

    }

-- Will not find matching glue code, but will work at runtime if we do:

    @When("^a Prepaid Security package is Active$")
    public void activitSecurityPackage(String packageType) {

    }

    @When("^a Monthly Security package is Active$")
    public void activitSecurityPackage(String packageType) {

    }

**Comment by girijant** [comment] 2017-12-13 18:20
@norman-knott, @akshaykamath, 
Above issues for java8 environment are almost completed. Currently doing some testing. I will fire a build  once its done.

**Comment by girijant** [comment] 2017-12-22 12:40
@norman-knott, @akshaykamath,
Glad to announce the new release(0.0.20 version) of Cucumber-Eclipse plugin which supports cucumber-java8 Lambda Expressions. The Plugin is enhanced to support below features for cucumber-java8 Lambda Expressions :
- Content-Assistance populates all the steps used in lambda expressions.
- Matching of Glue-code for all the steps used in lambda expressions.
- By pressing 'F3' key on steps in feature file navigates to the corresponding lambda-expression steps. 

Please refer our wiki page of [Lambda Expression support for Cucumber-Java8](https://github.com/cucumber/cucumber-eclipse/wiki/Lambda-Expression-support-for-Cucumber-Java8) for detail information.
Please update the plugin with the latest '0.0.20' version and let me know if you face any issue.

Happy BDD-Automation !!!

Thanks,
-Girija

**Closed by girijant** 2017-12-22 12:40 UTC
Labels: bug

**Comment by arnina01** [comment] 2018-02-28 05:56
@girijant 
I still get warning message(does not have a matching glue code) in feature file by installing cucumber-eclipse plugin- 0.0.19/0.0.20/0.0.21.
Do you have any ideals on this?

**Comment by Flaburgan** [comment] 2018-02-28 09:25
@arnina01 please only use the last version of the plugin. Can you please try to close and re-open the feature file, to relaunch the checker? If the warning is still there, can you tell us if all steps are indicated as non-implemented or only a few? Which ones?

**Comment by amanmalhotragit** [comment] 2018-03-27 10:36
Hi @girijant . I am new to Cucumber. I have written single feature file with 3 scenarios. When I have installed cucumber-plugin. Feature File is showing me error in each step as <b>"Step 'I am on XYZ login page' does not have a matching glue code"</b>. My project was running well prior to installation of cucumber-plugin. 

Why I have used plugin then?
Need to use cucumber-plugin to visualise the feature file in attractive way.

Could you please help or guide me here. Screenshot attached herewith.

![image](https://user-images.githubusercontent.com/34330412/37962428-b18cc562-31d8-11e8-9afc-3d279fc20caa.png)

**Comment by amanmalhotragit** [comment] 2018-06-05 05:20
@bryanjb9 . It's working now. Thanks

**Comment by girijant** [comment] 2018-06-25 07:33
Thanks guys for your quick support towards the ticket. Let's make the best cucumber-plugin for eclipse platform.
Happy Cucumber Automation !!!
Thanks,
-Girija

**Comment by dvarshney86** [comment] 2019-09-13 14:08
I am still facing the problem despite doing all the suggested mods. 
![image](https://user-images.githubusercontent.com/21123194/64868981-aff79480-d640-11e9-8638-49f79c3d60f9.png)

**Comment by bryanjb9** [comment] 2019-09-13 18:09
Can I see the structure of your project, where are the features, the
runners and the steps?

**Comment by qvdk** [comment] 2019-09-13 20:55
@codermvn do you convert your project as cucumber project ?
This feature is available from the contextual menu on the project folder.

**Comment by codermvn** [comment] 2019-09-17 08:14
@girijant @qvdk
Code uploaded on thread https://github.com/cucumber/cucumber-eclipse/issues/257

**Comment by codermvn** [comment] 2019-09-17 08:23
> 
> 
> @codermvn do you convert your project as cucumber project ?
> This feature is available from the contextual menu on the project folder.

@qvdk : Yes converted it to Cucumber Project, but still facing the same problem. Thanks.

**Comment by qvdk** [comment] 2019-09-17 11:44
@codermvn Sorry, I did not find any attachment on the thread #257. 
Could you post a link to a GitHub repository where we can find the project which reproduce your issue ?

**Comment by codermvn** [comment] 2019-09-17 15:16
@qvdk  Repo link is below for Sample Project
https://github.com/codermvn/CucumberSampleProject.git

**Comment by codermvn** [comment] 2019-09-18 12:42
> 
> 
> @codermvn Sorry, I did not find any attachment on the thread #257.
> Could you post a link to a GitHub repository where we can find the project which reproduce your issue ?

@qvdk Repo link is below for Sample Project
https://github.com/codermvn/CucumberSampleProject.git
Kindly let me know if you are unable to look at code.. thanks

**Comment by codermvn** [comment] 2019-09-20 05:41
Any help guys?

**Comment by mehtakovid** [comment] 2019-09-20 08:50
Facing the Same issue, reinstalled cucumber plugin after uninstalling. Project is converted to a Cucumber project as well. Nothing happens on click of recalculate steps. Went through multiple solutions here at GitHub as well as StackOverflow but nothing helps. It would be great to have a permanent solution to this.

**Comment by raghu7892** [comment] 2019-10-22 09:19
Hi all, even i am facing the same issues even after flowing all the above steps

**Comment by qvdk** [comment] 2019-10-22 09:45
Hi @raghu7892 

Do you try the solution describe in #376 please ?

**Comment by raghu7892** [comment] 2019-10-23 06:05
Ya tried but still i am facing the same issue can u please tell me the steps

**Comment by vinayakthakar** [comment] 2020-01-13 08:38
I am also facing the same issue, I have gone through the tickets mentioned above like #207, #223 etc but still the same issue. 
![image](https://user-images.githubusercontent.com/59821554/72241780-bd805380-360d-11ea-8f90-86f1cdb7370a.png)
I am using Eclipse 2019-06 and downloaded all the latest plugins. Still the same error. 

Feature file
Feature: Copy source file
  
  
Scenario: verify the copied file found on destination folder
  
    Given url 'http://localhost:8080/transactionservice/fileExists/'
    When method get
    Then method post

Runner file

package examples;


import org.junit.runner.RunWith;

import com.intuit.karate.junit4.Karate;

import cucumber.api.CucumberOptions;

@RunWith(Karate.class)

@CucumberOptions(
        glue = {"src/test/java/"} 
        )

public class Runner {

}

Project structure

![image](https://user-images.githubusercontent.com/59821554/72241919-1e0f9080-360e-11ea-876d-d38129c7a31c.png)

Please help

**Comment by qvdk** [comment] 2020-01-13 15:14
Hello @vinayakthakar 

1. check your are using the latest version 1.0.0-SNAPSHOT. See https://github.com/cucumber/cucumber-eclipse-update-site-snapshot
2. Configure your project as cucumber project. Right clic on your project > Configure > Convert as Cucumber project.

This will solve your issue.

**Comment by vinayakthakar** [comment] 2020-01-14 04:55
Thanks for the help. Its done
