### ISSUE TITLE
Unable to rerun a single feature in eclipse

### ISSUE THREAD

**Issue by karisN** [cucumber/cucumber-eclipse#359] opened 2019-04-17 20:21 UTC
Using the JUnit runner, I used to be able to right-click on a single test(.feature) and re-run, it now throws an error
![image](https://user-images.githubusercontent.com/4590565/56318208-538d5900-6124-11e9-8021-043ecd77076b.png)

`java.nio.file.InvalidPathException: Illegal char <:> at index 111: C:\......\.temp-Rerun .....CucumberRunner.Feature: About-classpath-arg-1555511782195.txt
    at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
    at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
    at java.io.File.toPath(File.java:2234)
    at org.eclipse.jdt.internal.launching.ClasspathShortener.createClassPathArgumentFile(ClasspathShortener.java:388)
    at org.eclipse.jdt.internal.launching.ClasspathShortener.shortenClasspathUsingClasspathArgumentFile(ClasspathShortener.java:298)
    at org.eclipse.jdt.internal.launching.ClasspathShortener.shortenClasspathIfNecessary(ClasspathShortener.java:220)
    at org.eclipse.jdt.internal.launching.ClasspathShortener.shortenCommandLineIfNecessary(ClasspathShortener.java:161)
    at org.eclipse.jdt.internal.launching.StandardVMRunner.getCommandLine(StandardVMRunner.java:469)
    at org.eclipse.jdt.internal.launching.StandardVMRunner.run(StandardVMRunner.java:492)
    at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.launch(JUnitLaunchConfigurationDelegate.java:267)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1029)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1243)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

It really doesn't like the colon in the Feature: (TEST NAME)
Is this a bug on eclipse, or would refactoring the regex of the test name fix the issue?

I've tried every combinations of the following:
eclipse version: jee-2018-12 + jee-2019-03
JDK: 1.8.0_201 + 11.0.2
cucumber-junit: 2.4.0 + 4.3.0

**Comment by laeubi** [comment] 2021-04-28 07:18
@karisN this is a duplicate of #14 please attach your case there or any further information (examples) that could help in resolving this issue.

**Closed by laeubi** 2021-04-28 07:18 UTC
