### ISSUE TITLE
While Launching feature file in Cucumber getting error:You are using deprecated Main class. Please use io.cucumber.core.cli.Main

### ISSUE THREAD

**Issue by rinky3211** [cucumber/cucumber-eclipse#428] opened 2021-03-28 05:59 UTC
Mar 28, 2021 11:24:33 AM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main
Mar 28, 2021 11:24:33 AM io.cucumber.core.runtime.FeaturePathFeatureSupplier get
WARNING: No features found at file:/E:/Selenium%20Demo/Cucumber_Practice/src/test/java/appFeatures/search.Feature

0 Scenarios
0 Steps
0m0.052s

┌───────────────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io          │
│ Activate publishing with one of the following:                                    │
│                                                                                   │
│ src/test/resources/cucumber.properties:          cucumber.publish.enabled=true    │
│ src/test/resources/junit-platform.properties:    cucumber.publish.enabled=true    │
│ Environment variable:                            CUCUMBER_PUBLISH_ENABLED=true    │
│ JUnit:                                           @CucumberOptions(publish = true) │
│                                                                                   │
│ More information at https://reports.cucumber.io/docs/cucumber-jvm                 │
│                                                                                   │
│ Disable this message with one of the following:                                   │
│                                                                                   │
│ src/test/resources/cucumber.properties:          cucumber.publish.quiet=true      │
│ src/test/resources/junit-platform.properties:    cucumber.publish.quiet=true      │
└───────────────────────────────────────────────────────────────────────────────────┘

**Comment by laeubi** [comment] 2021-03-28 06:04
This is a duplicate of #370

**Closed by laeubi** 2021-03-28 06:04 UTC

**Comment by Galphat** [comment] 2021-04-23 18:17
How to resolve it?

**Comment by ChPrasath** [comment] 2022-02-26 13:10
how to solve it..?
