### ISSUE TITLE
deprecated Main class warning while using Cucumber 6.1.1 

### ISSUE THREAD

**Issue by nukul25** [cucumber/cucumber-eclipse#415] opened 2020-06-24 18:50 UTC
I have installed Cucumber plugin in latest eclipse version and added dependencies for cucumber 6.1.1 via maven pom.xml

I have added all the necessary dependencies from the Github location :https://github.com/cucumber/cucumber-java-skeleton/blob/master/pom.xml

 

Now when I am trying to run my feature file which contains a scenario ,I am getting the warning as

Jun 23, 2020 7:03:00 PM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main

 

And as a result of this somehow execution is failing and my output is:

Jun 23, 2020 7:03:00 PM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main

Scenario: Add a menu item # src/test/java/linkedlearning/cucumbercourse/features/MenuManagement.feature:3

0 Scenarios
0 Steps
0m1.020s

 

Now in the cucumber-core-6.1.1.jar,I can see that it has 

--cucumber.api.cli package which has Main class and I suppose the execution is referring to this instead of

--io.cucumber.core.cli package which has Main class 

 
Console is not showing the usual suggestions of creating steps in step definition file and is blank.

Same I did by using Cucumber 5.6.0

Can you please help.

 My pom.xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>linkedlearning</groupId>
	<artifactId>cucumbercourse</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<name>cucumbercourse</name>
	
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
		<junit.version>4.13</junit.version>
		<cucumber.version>5.6.0</cucumber.version>
		<maven.compiler.version>3.8.1</maven.compiler.version>
	    <maven.compiler.source>1.7</maven.compiler.source>
		<maven.compiler.target>1.7</maven.compiler.target>
	</properties>

	<dependencies>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java8</artifactId>
			<version>${cucumber.version}</version>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-plugin</artifactId>
			<version>${cucumber.version}</version>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>${cucumber.version}</version>
			<type>pom</type>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				
				<plugin>
					<artifactId>maven-clean-plugin</artifactId>
					<version>3.1.0</version>
				</plugin>
				
				<plugin>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.0.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.8.0</version>
				</plugin>
				<plugin>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.22.1</version>
				</plugin>
				<plugin>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.0.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-install-plugin</artifactId>
					<version>2.5.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>2.8.2</version>
				</plugin>
				
				<plugin>
					<artifactId>maven-site-plugin</artifactId>
					<version>3.7.1</version>
				</plugin>
				<plugin>
					<artifactId>maven-project-info-reports-plugin</artifactId>
					<version>3.0.0</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>

Thanks

**Comment by mpkorstanje** [comment] 2020-06-24 19:52
The eclipse plugin launches Cucumber via the cli runner and is using the old main method.

https://github.com/cucumber/cucumber-eclipse/blob/606905b84cd31eeb588434b52cb29dd0740cb630/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/launching/CucumberFeatureLaunchConstants.java#L9

**Comment by nukul25** [comment] 2020-06-25 07:09
> The eclipse plugin launches Cucumber via the cli runner and is using the old main method.
> 
> https://github.com/cucumber/cucumber-eclipse/blob/606905b84cd31eeb588434b52cb29dd0740cb630/cucumber.eclipse.editor/src/main/java/cucumber/eclipse/launching/CucumberFeatureLaunchConstants.java#L9

If we uninstall Cucumber eclipse plugin then obviously we will not get the option of running Feature File only.

**Comment by nukul25** [comment] 2020-06-25 07:12
> I don't quite understand what's going on here. Is this a warning that is only shown when executing from Eclipse?
> 
> Do you get the same warning if you run `mvn test` in a terminal?


Hello
If i understood correctly,running the command mvn test from the command line(which is opened from the locaion of pom) will result in success sincewe have default test class called App.test which contains prin HELLO WORLD.
My concern is when I am running feature file only ,i got the issue as mentioned above.
Thanks

**Comment by manishbarthwal2410** [comment] 2020-06-26 02:22
I am also getting similar issue with 4.7.4 version

**Comment by nukul25** [comment] 2020-06-30 08:07
Hello Team

Any updates on the issue.?I tried with different version such as 5.6.0 and also faced the same issue.
Can you please help

**Comment by Davidj361** [comment] 2020-10-17 00:57
Getting the same problem with the plugin.
I am using this dependency:
```
<dependency>
	    <groupId>io.cucumber</groupId>
	    <artifactId>cucumber-java</artifactId>
	    <version>6.8.1</version>
	</dependency>
```

**Comment by brianle19** [comment] 2020-11-05 04:09
Any update? I have the same problem when upgraded project to cucumber 6.x

**Comment by muthu2490** [comment] 2020-11-22 21:39
Having the same issue Anyone found any solution for this?

**Comment by CHANDUGOUD229** [comment] 2020-12-16 19:53
Having the same issue Anyone found any solution for this pls update

**Comment by Ilkhomdzhon** [comment] 2021-01-16 07:22
Jan 16, 2021 2:17:50 AM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main

VERSION OF CUCUMBER IS 6.9.0
 

SAME HERE , GETTING ERROR

**Comment by timhunt** [comment] 2021-03-01 13:14
I think this is a duplicate of #370.

**Comment by shraddhabhalsing** [comment] 2021-03-22 10:12
Any update on deprecated Main class warning while using Cucumber 6.0 onwards version

**Comment by chetanSrajiv** [comment] 2021-03-26 04:19
it worked for me when i downgraded my testng dependency version from 7.4.0 to 7.1.0. try adding this dependency to your pom.xml

		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.1.0</version>
		</dependency>

**Comment by laeubi** [comment] 2021-03-28 06:04
This is a duplicate of #370

**Comment by anileapen** [comment] 2021-09-15 07:08
I have the sane problem . My pom.xml is below:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.aspectproject</groupId>
  <artifactId>CucumberAspectProject</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <dependencies>
  <!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-java -->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>6.11.0</version>
</dependency>

<!-- https://mvnrepository.com/artifact/net.sourceforge.cobertura/cobertura -->
<dependency>
    <groupId>net.sourceforge.cobertura</groupId>
    <artifactId>cobertura</artifactId>
    <version>2.1.1</version>
    <scope>test</scope>
</dependency>

<!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.141.59</version>
</dependency>


<dependency>
    <groupId>com.sun</groupId>
    <artifactId>tools</artifactId>
    <version>1.8</version>
    <scope>system</scope>
    <systemPath>C:\Program Files\Java\jdk-11.0.11\lib\tools.jar</systemPath>
</dependency>


<!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-core -->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-core</artifactId>
    <version>6.11.0</version>
</dependency>


  <!-- https://mvnrepository.com/artifact/junit/junit -->
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.13.2</version>
    <scope>test</scope>
</dependency>
  
 <!-- https://mvnrepository.com/artifact/org.hamcrest/hamcrest-core -->
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-core</artifactId>
    <version>2.2</version>
    <scope>test</scope>
</dependency>
 
 <!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-html -->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-html</artifactId>
    <version>0.2.7</version>
</dependency>
 
  
  <!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-junit -->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>6.11.0</version>
 
</dependency>
<!-- https://mvnrepository.com/artifact/net.masterthought/cucumber-reporting -->
<dependency>
    <groupId>net.masterthought</groupId>
    <artifactId>cucumber-reporting</artifactId>
    <version>5.6.0</version>
</dependency>

<!-- https://mvnrepository.com/artifact/io.cucumber/gherkin -->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>gherkin</artifactId>
    <version>3.2.0</version>
</dependency>

<!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-jvm-deps -->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-jvm-deps</artifactId>
    <version>1.0.6</version>
    <scope>provided</scope>
</dependency>

  
  <!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-testng -->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-testng</artifactId>
    <version>6.11.0</version>
</dependency>


    <dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-launcher</artifactId>
    <version>1.5.1</version>
    <scope>test</scope>
</dependency>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
   </dependencies>
</project>
Could someone help please?

**Comment by laeubi** [comment] 2021-09-15 07:22
This is not a problem but a warning, there will be no "fix" unless someone opens a PR for this to the `v1.x` branch.

We are currently developing a new version of the cucumber-plugin with improved support for more recent cucumber versions, if you like try out the following update-site (please uninstall the old plugin before):
https://cucumber.github.io/cucumber-eclipse/update-site/main/

**Comment by dineshvy** [comment] 2022-07-11 12:03
I am still facing this issue and not getting resolution for this. Can anyone please help me.

**Comment by bharadwaj92-qa** [comment] 2022-08-18 11:21
I see this issue has been closed but no where I see the solution.
 @laeubi could you please help me ?

**Comment by reena112556** [comment] 2022-09-14 06:55
Hi,
I am facing the same issue.

Sep 14, 2022 12:20:02 PM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main
Sep 14, 2022 12:20:03 PM io.cucumber.core.runtime.FeaturePathFeatureSupplier get
WARNING: No features found at file:/C:/Users/REENA/OneDrive%20-%20Capgemini/Desktop/Eclipse/OCEtest/src/test/resources/Features/offercreation.Feature

If you have any solution here please share here

Thanks!

**Comment by suprithad** [comment] 2022-09-16 04:34
Can someone provide the solution for this issue please.

**Comment by laeubi** [comment] 2022-09-16 05:43
Please see https://github.com/cucumber/cucumber-eclipse/issues/415#issuecomment-919766422

**Closed** 2022-09-16 07:13 UTC
Labels: :pray: help wanted, v1.x

**Comment by sabirmulla007** [comment] 2022-10-20 15:08
> Having the same issue Anyone found any solution for this?

yes. same issue of deprecated class but my browser is not opening.

**Comment by sabirmulla007** [comment] 2022-10-20 15:08
same issue of deprecated class but my browser is not opening.

**Comment by KendreMohini** [comment] 2023-02-21 09:17
Build Path-> check -> Junit is added or not and also check for related libraries -> if not then-> Add libraries -> Add Junit -> Apply and close. 

try with this. (I have just created demo cucumber project after done with this steps my warning was gone.)

**Comment by manojmore123** [comment] 2023-05-20 05:24
> I have installed Cucumber plugin in latest eclipse version and added dependencies for cucumber 6.1.1 via maven pom.xml
> 
> I have added all the necessary dependencies from the Github location :https://github.com/cucumber/cucumber-java-skeleton/blob/master/pom.xml
> 
> Now when I am trying to run my feature file which contains a scenario ,I am getting the warning as
> 
> Jun 23, 2020 7:03:00 PM cucumber.api.cli.Main run WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main
> 
> And as a result of this somehow execution is failing and my output is:
> 
> Jun 23, 2020 7:03:00 PM cucumber.api.cli.Main run WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main
> 
> Scenario: Add a menu item # src/test/java/linkedlearning/cucumbercourse/features/MenuManagement.feature:3
> 
> 0 Scenarios 0 Steps 0m1.020s
> 
> Now in the cucumber-core-6.1.1.jar,I can see that it has
> 
> --cucumber.api.cli package which has Main class and I suppose the execution is referring to this instead of
> 
> --io.cucumber.core.cli package which has Main class
> 
> Console is not showing the usual suggestions of creating steps in step definition file and is blank.
> 
> Same I did by using Cucumber 5.6.0
> 
> Can you please help.
> 
> My pom.xml
> 
> 4.0.0
> 
> ```
> <groupId>linkedlearning</groupId>
> <artifactId>cucumbercourse</artifactId>
> <version>0.0.1-SNAPSHOT</version>
> 
> <name>cucumbercourse</name>
> 
> <url>http://maven.apache.org</url>
> 
> <properties>
> 	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
> 	<java.version>1.8</java.version>
> 	<junit.version>4.13</junit.version>
> 	<cucumber.version>5.6.0</cucumber.version>
> 	<maven.compiler.version>3.8.1</maven.compiler.version>
>     <maven.compiler.source>1.7</maven.compiler.source>
> 	<maven.compiler.target>1.7</maven.compiler.target>
> </properties>
> 
> <dependencies>
> 
> 	<dependency>
> 		<groupId>io.cucumber</groupId>
> 		<artifactId>cucumber-core</artifactId>
> 		<version>${cucumber.version}</version>
> 		<scope>test</scope>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>io.cucumber</groupId>
> 		<artifactId>cucumber-java</artifactId>
> 		<version>${cucumber.version}</version>
> 		<scope>test</scope>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>io.cucumber</groupId>
> 		<artifactId>cucumber-junit</artifactId>
> 		<version>${cucumber.version}</version>
> 		<scope>test</scope>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>junit</groupId>
> 		<artifactId>junit</artifactId>
> 		<version>${junit.version}</version>
> 		<scope>test</scope>
> 	</dependency>
> 
> 
> 
> 	<dependency>
> 		<groupId>io.cucumber</groupId>
> 		<artifactId>cucumber-java8</artifactId>
> 		<version>${cucumber.version}</version>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>io.cucumber</groupId>
> 		<artifactId>cucumber-plugin</artifactId>
> 		<version>${cucumber.version}</version>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>io.cucumber</groupId>
> 		<artifactId>cucumber-jvm</artifactId>
> 		<version>${cucumber.version}</version>
> 		<type>pom</type>
> 	</dependency>
> </dependencies>
> 
> <build>
> 	<pluginManagement>
> 		<plugins>
> 			
> 			<plugin>
> 				<artifactId>maven-clean-plugin</artifactId>
> 				<version>3.1.0</version>
> 			</plugin>
> 			
> 			<plugin>
> 				<artifactId>maven-resources-plugin</artifactId>
> 				<version>3.0.2</version>
> 			</plugin>
> 			<plugin>
> 				<artifactId>maven-compiler-plugin</artifactId>
> 				<version>3.8.0</version>
> 			</plugin>
> 			<plugin>
> 				<artifactId>maven-surefire-plugin</artifactId>
> 				<version>2.22.1</version>
> 			</plugin>
> 			<plugin>
> 				<artifactId>maven-jar-plugin</artifactId>
> 				<version>3.0.2</version>
> 			</plugin>
> 			<plugin>
> 				<artifactId>maven-install-plugin</artifactId>
> 				<version>2.5.2</version>
> 			</plugin>
> 			<plugin>
> 				<artifactId>maven-deploy-plugin</artifactId>
> 				<version>2.8.2</version>
> 			</plugin>
> 			
> 			<plugin>
> 				<artifactId>maven-site-plugin</artifactId>
> 				<version>3.7.1</version>
> 			</plugin>
> 			<plugin>
> 				<artifactId>maven-project-info-reports-plugin</artifactId>
> 				<version>3.0.0</version>
> 			</plugin>
> 		</plugins>
> 	</pluginManagement>
> </build>
> ```
> 
> Than

**Comment by manojmore123** [comment] 2023-05-20 05:25
Please recheck feature file, may be you syntactical mistake

**Comment by AshokMarrapu** [comment] 2023-11-28 02:29
Hi I have the same issue. Can someone help me with latest stable dependencies that might work.

My console shows like this:

Nov 28, 2023 7:54:51 AM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main

0 Scenarios
0 Steps
0m0.057s


┌───────────────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io          │
│ Activate publishing with one of the following:                                    │
│                                                                                   │
│ src/test/resources/cucumber.properties:          cucumber.publish.enabled=true    │
│ src/test/resources/junit-platform.properties:    cucumber.publish.enabled=true    │
│ Environment variable:                            CUCUMBER_PUBLISH_ENABLED=true    │
│ JUnit:                                           @CucumberOptions(publish = true) │
│                                                                                   │
│ More information at https://cucumber.io/docs/cucumber/environment-variables/      │
│                                                                                   │
│ Disable this message with one of the following:                                   │
│                                                                                   │
│ src/test/resources/cucumber.properties:          cucumber.publish.quiet=true      │
│ src/test/resources/junit-platform.properties:    cucumber.publish.quiet=true      │

**Comment by dineshvy** [comment] 2023-11-28 03:23
After I added all the jars with the specific versions as mentioned in the
video, my issue got resolved. I did this 6 months back. You can also check.

Link- https://youtu.be/d56lRIAwQEI?si=dk_hOfsbHaYRClyT

**Comment by shahnawazm786** [comment] 2024-01-27 15:44
I am getting following error with latest version of cucumber.
my pom.xml file and error attached here under
**<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>

	<dependencies>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.17.0</version>
		</dependency>

		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>7.15.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>7.15.0</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>7.15.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>7.15.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-spring</artifactId>
			<version>7.15.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>gherkin</artifactId>
			<version>27.0.0</version>
		</dependency>


	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M5</version>
			</plugin>
		</plugins>
	</build>**




io.cucumber.core.exception.CompositeCucumberException: There were 2 exceptions. The details are in the stacktrace below.
	at io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)
	at io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:109)
	at io.cucumber.core.runtime.CucumberExecutionContext.runFeatures(CucumberExecutionContext.java:155)
	at io.cucumber.junit.Cucumber$StartAndFinishTestRun.evaluate(Cucumber.java:226)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
	Suppressed: java.util.ServiceConfigurationError: io.cucumber.core.backend.ObjectFactory: io.cucumber.spring.SpringFactory Unable to get public no-arg constructor
		at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
		at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:673)
		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
		at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
		at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
		at io.cucumber.core.runtime.ObjectFactoryServiceLoader.loadSingleObjectFactoryOrDefault(ObjectFactoryServiceLoader.java:72)
		at io.cucumber.core.runtime.ObjectFactoryServiceLoader.loadObjectFactory(ObjectFactoryServiceLoader.java:43)
		at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
		at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
		at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
		at io.cucumber.core.runtime.ThreadLocalObjectFactorySupplier.get(ThreadLocalObjectFactorySupplier.java:18)
		at io.cucumber.core.runtime.BackendServiceLoader.loadBackends(BackendServiceLoader.java:48)
		at io.cucumber.core.runtime.BackendServiceLoader.get(BackendServiceLoader.java:37)
		at io.cucumber.core.runtime.BackendServiceLoader.get(BackendServiceLoader.java:33)
		at io.cucumber.core.runtime.ThreadLocalRunnerSupplier.createRunner(ThreadLocalRunnerSupplier.java:46)
		at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
		at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
		at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
		at io.cucumber.core.runtime.ThreadLocalRunnerSupplier.get(ThreadLocalRunnerSupplier.java:40)
		at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
		at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:141)
		at io.cucumber.core.runtime.CucumberExecutionContext.runBeforeAllHooks(CucumberExecutionContext.java:93)
		at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runFeatures$6(CucumberExecutionContext.java:147)
		at io.cucumber.core.runtime.CucumberExecutionContext.execute(CucumberExecutionContext.java:163)
		at io.cucumber.core.runtime.CucumberExecutionContext.runFeatures(CucumberExecutionContext.java:146)
		... 9 more
	Caused by: java.lang.NoClassDefFoundError: org/springframework/beans/BeansException
		at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
		at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
		at java.base/java.lang.Class.getConstructor0(Class.java:3342)
		at java.base/java.lang.Class.getConstructor(Class.java:2151)
		at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:660)
		at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:657)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:668)
		... 33 more
	Caused by: java.lang.ClassNotFoundException: org.springframework.beans.BeansException
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
		at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
		... 41 more
	Suppressed: java.util.ServiceConfigurationError: io.cucumber.core.backend.ObjectFactory: io.cucumber.spring.SpringFactory Unable to get public no-arg constructor
		at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
		at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:673)
		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
		at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
		at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
		at io.cucumber.core.runtime.ObjectFactoryServiceLoader.loadSingleObjectFactoryOrDefault(ObjectFactoryServiceLoader.java:72)
		at io.cucumber.core.runtime.ObjectFactoryServiceLoader.loadObjectFactory(ObjectFactoryServiceLoader.java:43)
		at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
		at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
		at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
		at io.cucumber.core.runtime.ThreadLocalObjectFactorySupplier.get(ThreadLocalObjectFactorySupplier.java:18)
		at io.cucumber.core.runtime.BackendServiceLoader.loadBackends(BackendServiceLoader.java:48)
		at io.cucumber.core.runtime.BackendServiceLoader.get(BackendServiceLoader.java:37)
		at io.cucumber.core.runtime.BackendServiceLoader.get(BackendServiceLoader.java:33)
		at io.cucumber.core.runtime.ThreadLocalRunnerSupplier.createRunner(ThreadLocalRunnerSupplier.java:46)
		at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
		at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
		at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
		at io.cucumber.core.runtime.ThreadLocalRunnerSupplier.get(ThreadLocalRunnerSupplier.java:40)
		at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
		at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:141)
		at io.cucumber.core.runtime.CucumberExecutionContext.runAfterAllHooks(CucumberExecutionContext.java:98)
		at io.cucumber.core.runtime.CucumberExecutionContext.execute(CucumberExecutionContext.java:163)
		at io.cucumber.core.runtime.CucumberExecutionContext.runFeatures(CucumberExecutionContext.java:151)
		... 9 more
	Caused by: java.lang.NoClassDefFoundError: org/springframework/beans/BeansException
		at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
		at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
		at java.base/java.lang.Class.getConstructor0(Class.java:3342)
		at java.base/java.lang.Class.getConstructor(Class.java:2151)
		at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:660)
		at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:657)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:668)
		... 32 more
	Caused by: java.lang.ClassNotFoundException: org.springframework.beans.BeansException
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
		at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
		... 40 more
