### ISSUE TITLE
Error: Could not find or load main class cucumber.api.cli.Main

### ISSUE THREAD

**Issue by jainsampada** [cucumber/cucumber-eclipse#330] opened 2019-01-22 10:54 UTC
Error: Could not find or load main class cucumber.api.cli.Main while running feature file in Maven

**Comment by girijant** [comment] 2019-01-22 11:01
@jainsampada
Have you tried to it from Eclipse ??? Try it from command prompt without using Eclipse.
Please share the detail exception stack trace with your eclipse and cucumebr-plugin version. 

Thanks,
-Girija

**Comment by laeubi** [comment] 2019-05-02 06:59
I also see this problem, beside this the Run As>Cucumber-Feature is broken in recent eclipse versions, this is due to the unimplemented 
`void launch(ISelection selection, String mode)`

**Comment by laeubi** [comment] 2019-05-02 07:07
The problem seems that the classpath does only contain user entries when computed by the runner and not the eclipse classpath.

**Comment by laeubi** [comment] 2019-05-06 07:38
Duplicate of #190

**Closed by laeubi** 2019-05-06 07:38 UTC

**Comment by shilpijoshi22** [comment] 2020-08-02 08:00
> @jainsampada
> Have you tried it from Eclipse or without Eclipse??? Try it from command prompt without using Eclipse.
> Please share the detail exception stack trace with your eclipse and cucumebr-plugin version.
> 
> Thanks,
> -Girija

@girijant I am using command promt to run this. But I am unable to understand the syntax and use. Can you please help

**Comment by 11nidhi** [comment] 2022-11-11 17:26
> I also see this problem, beside this the Run As>Cucumber-Feature is broken in recent eclipse versions, this is due to the unimplemented `void launch(ISelection selection, String mode)`

Can you suggest any solutions?
Like i didn't get what to do exactly to resolve this
